// Code generated by MockGen. DO NOT EDIT.
// Source: indexprovider/engineproxy.go

// Package mock_engine is a generated GoMock package.
package mock_engine

import (
	context "context"
	reflect "reflect"

	provider "github.com/filecoin-project/index-provider"
	metadata "github.com/filecoin-project/index-provider/metadata"
	gomock "github.com/golang/mock/gomock"
	cid "github.com/ipfs/go-cid"
	peer "github.com/libp2p/go-libp2p-core/peer"
)

// MockEngineProxy is a mock of EngineProxy interface.
type MockEngineProxy struct {
	ctrl     *gomock.Controller
	recorder *MockEngineProxyMockRecorder
}

// MockEngineProxyMockRecorder is the mock recorder for MockEngineProxy.
type MockEngineProxyMockRecorder struct {
	mock *MockEngineProxy
}

// NewMockEngineProxy creates a new mock instance.
func NewMockEngineProxy(ctrl *gomock.Controller) *MockEngineProxy {
	mock := &MockEngineProxy{ctrl: ctrl}
	mock.recorder = &MockEngineProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineProxy) EXPECT() *MockEngineProxyMockRecorder {
	return m.recorder
}

// NotifyPut mocks base method.
func (m *MockEngineProxy) NotifyPut(ctx context.Context, provider *peer.AddrInfo, contextID []byte, md metadata.Metadata) (cid.Cid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPut", ctx, provider, contextID, md)
	ret0, _ := ret[0].(cid.Cid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyPut indicates an expected call of NotifyPut.
func (mr *MockEngineProxyMockRecorder) NotifyPut(ctx, provider, contextID, md interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPut", reflect.TypeOf((*MockEngineProxy)(nil).NotifyPut), ctx, provider, contextID, md)
}

// NotifyRemove mocks base method.
func (m *MockEngineProxy) NotifyRemove(ctx context.Context, providerID peer.ID, contextID []byte) (cid.Cid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyRemove", ctx, providerID, contextID)
	ret0, _ := ret[0].(cid.Cid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyRemove indicates an expected call of NotifyRemove.
func (mr *MockEngineProxyMockRecorder) NotifyRemove(ctx, providerID, contextID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyRemove", reflect.TypeOf((*MockEngineProxy)(nil).NotifyRemove), ctx, providerID, contextID)
}

// RegisterMultihashLister mocks base method.
func (m *MockEngineProxy) RegisterMultihashLister(l provider.MultihashLister) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterMultihashLister", l)
}

// RegisterMultihashLister indicates an expected call of RegisterMultihashLister.
func (mr *MockEngineProxyMockRecorder) RegisterMultihashLister(l interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMultihashLister", reflect.TypeOf((*MockEngineProxy)(nil).RegisterMultihashLister), l)
}

// Shutdown mocks base method.
func (m *MockEngineProxy) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockEngineProxyMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockEngineProxy)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockEngineProxy) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockEngineProxyMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEngineProxy)(nil).Start), ctx)
}
