name: Check GoReleaser Config
on:
  pull_request:
    paths: [ '.goreleaser.yaml' ]

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"
      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: check
